[{
    "OS": "Android 11 OS",
    "UI": "MIUI 12.5",
    "dimensions": "164.1 x 76.9 x 8.8 mm",
    "weight": "204 g",
    "sim": "Dual Sim, Dual Standby (Nano-SIM)",
    "colors": "Meteorite Gray, Moonlight White, Celestial Blue",
    "twoGBand": "SIM1: GSM 850 / 900 / 1800 / 1900 SIM2: GSM 850 / 900 / 1800 / 1900 ",
    "threeGBand": "HSDPA 850 / 900 / 1700(AWS) / 1900 / 2100 ",
    "fourGBand": "LTE band 1(2100), 3(1800), 7(2600), 8(900), 20(800) ",
    "fiveGBand": "5G SA/NSA ",
    "CPU": "Octa-core (1 x 2.84 GHz Kryo 680 + 3 x 2.42 GHz Kryo 680 + 4 x 1.80 GHz Kryo 680)",
    "chipSet": "Qualcomm SM8350 Snapdragon 888 5G (5 nm) ",
    "GPU": "Adreno 660",
    "technology": "AMOLED, Dolby Vision, 1B colors, Multitouch",
    "size": "6.7 Inches",
    "resolution": "1080 x 2400 Pixels (~395 PPI)",
    "protection": "Corning Gorilla Glass Victus",
    "extraFeatures": "120Hz, HDR10+, 800 nits (typ), 1000 nits (peak)",
    "ram": 12,
    "rom": 256,
    "card": 16,
    "main": "Rile Camera: 108 MP, f/1.8, 26mm (wide), 1/1.52, PDAF + 8 MP, f/2.2, (ultrawide), 1/4 + 5 MP, f/2.4, 50mm (telephoto macro), 1/5.0, AF, dual-LED dual-tone flash",
    "features": "Super Night Mode 2.0, Ge-tagging, Phase detection, Panorama, HDR, Video (1080p@30fps)",
    "font": "8 MP, With Dual LED Flash",
    "WLAN": "Wi-Fi 802.11 b/g/n, hotspot",
    "bluetooth": "v5.1 with A2DP, LE",
    "GPS": "Yes + A-GPS support",
    "radio": "FM Radio",
    "USB": "microUSB 2.0, USB On-The-Go",
    "NFC": "No",
    "data": "GPRS, Edge, 3G (HSPA 42.2/5.76 Mbps), 4G (LTE Cat4 150/50 Mbps)",
    "sensor": "Accelerometer, Face Unlock, Fingerprint, Proximity",
    "audio": "3.5mm Audio Jack, MP4/H.264 player, MP3/WAV/FLAC/eAAC+ player, Speaker Phone",
    "browser": "HTML5",
    "messaging": "SMS(threaded view), MMS, Email, Push Mail, IM",
    "games": "Built-in + Downloadable",
    "torch": "Yes",
    "extra": "Super Boost System Optimization, Photo/video editor, Document viewer",
    "brandName": "infinix",
    "modelNumber": "hot2",
    "capacity": "(Li-Po Non removable), 4500 mAh",
    "price": {
        "inRS": "32000",
        "inUSD": "155"
    },
    "shortDescription": "Tecno Spark 8 Pro price in Pakistan is Rs. 24,999. Official dealers and warranty providers regulate the retail price of Tecno mobile products in official warranty.",
    "longDescription": "Tecno is working on its new Spark 8 which has got a moniker Pro at the end. The Chinses company Tecno has officially launched its all-new smartphone of its Spark-series. The upcoming handset of the company is a mid-ranger, the smartphone will be launched in Bangladesh and it will be named a Tecno Spark 8 Pro. The new smartphone will be a MediaTek Helio G85 SoC chipset. This is a powerful chipset that will empower the upcoming all-new smartphone Tecno's Spark 8 Pro to provide the user with high-end performance, and also there is a 2.0 GHz Octa-Core processor under the hood of this smartphone. Also, there is a GPU of Mali-G52 inside this handset. The Tecno Spark 8's going to have 6.8 Inches which is a massive screen, and to provide the user with full HD plus the resolution of 1080 x 2400 Pixels. And there is an IPS LCD Capacitive Touchscreen display. The new Spark 8 Pro by Tecno is having an upcoming smartphone with 4 gigabytes RAM, which is the highest point of RAM used in this smartphone so you can say that your phone is going to run at a super-fast speed because of its powerful RAM. The built-in storage capacity of the Tecno 8 Pro is 64 gigabytes which means that the capacity of your data is unlimited. On the rear of the upcoming new Tecno Spark's 8 Pro, there is a Triple Camera setup. The main sensor of the phone will be 48 megapixels and others are not confirmed yet. The selfie shooter will be 8 megapixels. The upcoming smartphone Spark 8 Pro has got a rear-mounted fingerprint reader to secure the data on the smartphone and only allow the authorized person. The all-new handset will be fueled with a Non-removable Li-Po 5000 mAh battery that will carry support for Fast charging of 33W. Samsung and other tech giants will face serious competition when the coming smartphone 8 Pro will release."

}]